danshadybusiness/danshadybusiness/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('demo/', include('demo.urls')),
    path('demo/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
]

danshadybusiness/demo/urls.py
from django.urls import path
from . import views

app_name = 'demo'
urlpatterns = [
    path('', views.index, name='Login'),
    path('loggedIn', views.loggedIn, name='Logged_In'),
    path('logoutView', views.logoutView, name='logoutView'),
    path('cars', views.cars, name='cars'),
    path('addCar', views.addCar, name='addCar')
]

danshadybusiness/product/urls.py
from django.urls import path
from . import views
app_name = 'product'


urlpatterns = [

    path('', views.loginTest, name = "loginTest"),
    path('addFunds/', views.addFunds, name='addFunds'),
    # path('account/', views.customUser, name = "customUser"),
    path('addCarPage/', views.addCarPage, name = 'addCarPage'),
    path('addCarPage/addCar/',views.addCar, name='addCar'),
    path('index/', views.index, name='index'),
    path('aboutUs/', views.aboutUs, name='aboutUs'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('service/', views.service, name='service'),
    path('availableCars/', views.availableCars, name="availableCars"),
    path('account/logout/', views.logoutPage, name = "logoutPage"),
    path('reservation/', views.reservation, name='reservation'),


    path('account/', views.account, name='account'),

    
    path('hire/', views.hirePage, name='hirePage'),
    path('createserviceticket/', views.createTicketPage, name='createTicketPage'),
    path('employeeHours/', views.employeeHours, name='employeeHours'),
    path('employeeHours/logHours/',views.logHours, name='logHours'),
    path('payEmployeePage/', views.payEmployeePage, name="payEmployeePage"),
    path('payEmployeePage/payAll/', views.payAll, name='payAll'),
    path('reservation/<int:car_id>/<str:startDate>/<str:endDate>/', views.displayCar, name = 'displayCar'),
    path('reservation/<int:car_id>/reserveCar/', views.reserveCar, name = 'reserveCar'),
    path('inventory/',views.inventory,name = "inventory"),
    path('overdueReservations/',views.overdueReservations, name = "overdueReservations"),
    path('overdueReservations/lojackCar/',views.lojackCar, name='lojackCar'),
    path('account/currentReservations/',views.currentReservations, name = "currentReservations"),
    path('account/currentReservations/returnCar/',views.returnCar,name = "returnCar"),



]

danshadybusiness/product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver




class CustomUser(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    balance = models.FloatField(default = 0.0)
    hours = models.FloatField(default = 0.0)

    def addFunds(self,amount):
        self.balance += amount
    
    def addHours(self,amount):
        self.hours += amount
    
    def __str__(self):
        return self.user.username
    

#this method is to create CustomUser when User is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        CustomUser.objects.create(user=instance)

#this method to update profile when user is updated
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.customuser.save()


class Car(models.Model):
    name = models.CharField(max_length=20)
    price = models.FloatField()

    def __str__(self):
        return self.name
    

class CarReservation(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    startDate = models.DateField()
    endDate = models.DateField()
    lojacked = models.BooleanField(default=False)
    insurance = models.BooleanField(default=False)


    def __str__(self):
        return "User: "+self.user.user.username +" Car: "+self.car.name+ " ("+str(self.startDate) + " -> " + str(self.endDate) + ")"



# Create your models here.

class ServiceTicket(models.Model):
    customerId = models.IntegerField()
    carId = models.IntegerField()
    assigned = models.BooleanField(default=False)

    def __str__(self):
        return User.objects.get(pk=self.customerId).username + ' '+ str(Car.objects.get(pk = self.carId))

danshadybusiness/product/views.py
from django.shortcuts import render
from product.models import CustomUser, Car, ServiceTicket, CarReservation
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.contrib.auth.models import Group, Permission, User
from datetime import datetime, date



@login_required(login_url='product:loginTest')
def addFunds(request):
    customUser = CustomUser.objects.get(user = request.user)
    if request.method == 'POST':
        if "10" in request.POST:
            customUser.addFunds(10.0)
            customUser.save()
            return redirect(reverse("product:addFunds"))
        elif "25" in request.POST:
            customUser.addFunds(25.0)
            customUser.save()
            return redirect(reverse("product:addFunds"))
        elif "50" in request.POST:
            customUser.addFunds(50.0)
            customUser.save()
            return redirect(reverse("product:addFunds"))
        elif "100" in request.POST:
            customUser.addFunds(100.0)
            customUser.save()
            return redirect(reverse("product:addFunds"))
        elif "custom" in request.POST:
            customUser.addFunds(float(request.POST["custom"]))
            customUser.save()
            return redirect(reverse("product:addFunds"))

    return render(request, 'product/addFunds.html', {'customUser': customUser})


@login_required(login_url='product:loginTest')
def aboutUs(request):
    return render(request, 'product/aboutUs.html', {})

@login_required(login_url='product:loginTest')
def index(request):
    customUser = CustomUser.objects.get(user = request.user)
    return render(request, 'product/index.html', {'customUser': customUser})
@login_required(login_url='product:loginTest')
def reservation(request):
    return render(request, 'product/reservation.html', {})

@login_required(login_url='product:loginTest')
def hire(request):
    return render(request, 'product/hire.html', {})

@login_required(login_url='product:loginTest')
def account(request):
    now = date.today()
    customUser = CustomUser.objects.get(user = request.user)
    list = []
    for reservation in customUser.carreservation_set.all():
        if reservation.endDate >= now:
            list.append(reservation)
    return render(request, 'product/account.html', {'customUser': customUser,'reservations':list})

def loginTest(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect(reverse('product:index'))
        
        else:
            context = {'errorMessage': "Invalid login credentials, please try again!"}
            return render(request, 'product/login.html', context)
    if request.user.is_authenticated:
        return redirect(reverse('product:account'))

    
    return render(request, 'product/login.html')

@login_required(login_url='product:loginTest')
def logoutPage(request):
        logout(request)
        return redirect(reverse('product:loginTest'))

@login_required(login_url='product:loginTest')
def addCarPage(request):
    if not request.user.has_perm('auth.Manager'):
        return redirect(reverse('product:account'))

    context = CustomUser.objects.get(user=request.user)
    return render(request, 'product/addCarPage.html', {'context':context})

@login_required(login_url='product:loginTest')
def addCar(request):
    ##this method adds cars to the database
    customUser = CustomUser.objects.get(user = request.user)
    if customUser.balance < float(request.POST['carPrice']):
        return render(request, 'product/addCarPage.html', {'errorMessage': "Insufficient funds, cannot purchase car", 'context':customUser})

    customUser.addFunds(float(request.POST['carPrice']) * -1)
    customUser.save()
    car = Car(name = request.POST['carName'], price = float(request.POST['carPrice']))
    car.save()
    return redirect(reverse('product:addCarPage'))



def availableCars(request):
    resp = {}
    try:
        startDate = request.GET.get('startDate')
        endDate = request.GET.get('endDate')
        carPrice = request.GET.get('carPrice')
        startDate = datetime.strptime(startDate, '%Y-%m-%d').date()
        endDate = datetime.strptime(endDate, '%Y-%m-%d').date()
    except:
        resp['error'] = "Please Input Start and End Date"
        return JsonResponse(resp)
    if startDate> endDate:
        resp['error'] = "End Date is before Start Date"
        return JsonResponse(resp)
    resp['start-date'] = startDate
    resp['end-date'] = endDate
    for car in Car.objects.all():
        addingCar = True
        if car.price != float(carPrice):
            continue
        if len(car.carreservation_set.all()) == 0 and car.price == float(carPrice):
            resp[str(car.id)] = car.name
        else:
            for reservation in car.carreservation_set.all():
                if (startDate <= reservation.endDate and startDate >= reservation.startDate) or (car.price != float(carPrice)):
                    addingCar = False
                    break
                if (endDate >= reservation.startDate and endDate <= reservation.endDate) or (car.price != float(carPrice)):
                    addingCar = False
                    break
                if (reservation.startDate >= startDate and reservation.startDate <= endDate) or (car.price != float(carPrice)):
                    addingCar = False
                    break
                if (reservation.endDate >= startDate and reservation.endDate <= endDate) or (car.price != float(carPrice)):
                    addingCar = False
                    break
            if addingCar:
                resp[str(car.id)] = car.name
                
    response = JsonResponse(resp)
    response['Access-Control-Allow-Origin'] = '*'

    return response

@login_required(login_url='product:loginTest')
def createTicketPage(request):
    # take an integer in a post
    # passes context with list of all current reservations in appropriate date window
    if request.method =='POST':
        reservation = CarReservation.get(id=request.POST['reservationId'])
        createTicket(CarReservation.meta.get_field('customerId'), CarReservation.meta.get_field('carId'))
    currentDate = date.today()
    validReservations = CarReservation.objects.exclude(startDate__gte=currentDate)
    return render(request, 'product/createTicketPage.html', {'validReservations' : validReservations})

@login_required(login_url='product:loginTest')
def createTicket(customerId, carId):
    ticket = ServiceTicket(customerId=customerId, carId=carId)
    ticket.save()

def terminate(request):
    serviceTicketId = request.POST['serviceTicketId']
    ServiceTicket.objects.filter(pk=serviceTicketId)

@login_required(login_url='product:loginTest')
def service(request):

    if request.method == 'POST':
        deleteList = []
        deleteList.append(request.POST.get('1st'))
        deleteList.append(request.POST.get('2nd'))
        deleteList.append(request.POST.get('3rd'))
        deleteTickets(deleteList)
    ticketList = ServiceTicket.objects.all()
    firstTickets = []
    if len(ticketList)<= 3:
        firstTickets = ticketList
    else :
        firstTickets = ticketList[:3]
    return render(request, 'product/serviceTicket.html', {'ticketList' : ticketList})

def deleteTickets(deleteList):
    ticketList = ServiceTicket.objects.all()
    firstTickets = []
    if len(ticketList) <= 3:
        firstTickets = ticketList
    else:
        firstTickets = ticketList[:3]
    for i in range(len(firstTickets)):
        if deleteList[i] == "on":
            customUserId = firstTickets[i].customerId
            customUser = CustomUser.objects.get(pk = customUserId)
            customUser.addFunds(-300.0)
            customUser.save()
            firstTickets[i].delete()


def signup(request):
    if request.method == 'POST':
        try:
            exists = CustomUser.objects.get(email = request.POST['email'])
            return render(request,"product/signup.html",{'error':"Email already exists"})
        except:
            user = User.objects.create_user(username = request.POST['email'],
                                            password = request.POST['password'], 
                                            email = request.POST['email'], 
                                            first_name = request.POST['firstName'], 
                                            last_name = request.POST['lastName'])
            user.save
            user.groups.add(Group.objects.get(name='User'))
            return render(request, 'product/login.html', {})
    return render(request,'product/signup.html', {})


@login_required(login_url='product:loginTest')
def employeeHours(request):
    if request.user.has_perm('auth.Employee'):
        return render(request,'product/reportHours.html')

    else:
        return redirect(reverse('product:account'))
    
@login_required(login_url='product:loginTest')
def logHours(request):
    if request.method == 'POST' and request.user.has_perm('auth.Employee'):
        totalHours = request.POST['hours']
        user = CustomUser.objects.get(user = request.user)
        user.addHours(float(totalHours))
        user.save()
        return redirect(reverse('product:account'))
    return redirect(reverse('product:employeeHours'))



@login_required(login_url='product:loginTest')
def payEmployeePage(request):
    if request.user.has_perm('auth.Manager'):
        employees = []
        for employee in CustomUser.objects.all():
            if employee.user.has_perm('auth.Employee'):

danshadybusiness/product/templates/product/addCarPage.html
<!DOCTYPE html>
<html>
  <head>
    <title>Add Car</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'product/style/headerStyle.css' %}">
    <link rel="stylesheet" href="{% static 'product/style/footerStyle.css' %}">
    <link rel="stylesheet" href="{% static 'product/style/style.css' %}">

    <script src="header.js"></script>


</head>
<body>
  {% include 'product/header.html' %}
  {% block content %}
  <div class="page">
    <div class="container">
      <div class="row">
        <h1 class="add-car-label col-xs-12 text-center">Add Car</h1>
        <form class="add-car-form" action="{% url 'product:addCar' %}" method="post">
            {% csrf_token %}
            <div class="col-sm-4"></div>
            <div class="car-details-ctn col-xs-12 col-sm-4">
              <label class="car-name" for="carName"><b>Car name</b></label>
              <input class="car-content car-name" type="text" placeholder="Enter Car name" name="carName" required>   
              <label class="car-price" for="carPrice"><b>Car Price</b></label>

              <!-- <label class="car-price" for="imageInput"><b>Car Image</b></label>
              <input  type="file" placeholder="Browse..." name="imageInput">        -->

              <input class="car-content car-price" type="number" placeholder="Enter Car Price" name="carPrice" required>     

              <button class="purchase-button button"type="submit">Purchase Car</button>       
            </div>
          </form>
          <h3 class="funds col-xs-12 text-center">Your current funds: {{context.balance}}</h3>
          <h2>{{errorMessage}}</h2>
      </div>
    </div>
    {% include 'product/footer.html' %}
    {% endblock %}
  </div>

</body>
</html>

danshadybusiness/product/templates/product/createTicketPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>Create a service ticket</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'product/style/createServiceStyle.css' %}">
    <link rel="stylesheet" href="{% static 'product/style/headerStyle.css' %}">
        <link rel="stylesheet" href="{% static 'product/style/footerStyle.css' %}">
</head>
<body>

{% block content %}
 {% include 'product/header.html' %}
<div id="titleDiv">
    <h3>Customer late on a rental return? Did they rent a car without insurance? Lojack 'em here!</h3>
</div>
<div id="formDiv">
    <form action="{% url 'product:lojackCar' %}" method="post">
        {% csrf_token %}
        <label for="options">Select a car to lo-jack</label>
        <select id="options" name="options">
            {% if reservations %}
    {% for reservation in reservations %}
        <option name="reservationId" id="reservationId" value="{{reservation.id}}">{{reservation}}</option>
        {% endfor %}
            {% else %}
            <option name="reservationID">No rentals available to lojack! Rent more cars out!</option>
            {% endif %}
            </select>
        <div>
            {% if reservations %}
            <button type="submit">Lojack car #{{reservation.car.id}}</button>
            {% endif %}
        </div>
    </form>
</div>
 {% include 'product/footer.html' %}
        {% endblock %}
</body>
</html>

danshadybusiness/product/templates/product/customUser.html
<!DOCTYPE html>
<html>
    <head>
        <h1>
        Your username: {{customUser.user.username}}
    </h1>
    <h1>
        Your balance: {{customUser.balance}}
        </h1>
        {% if perms.auth.Employee %}
        <h1>
            Your hours logged: {{customUser.hours}}
        </h1>
        {% endif %}
    </head>
<body>
    <div class="page">
        <h4>Your Car Reservations:</h4>
        <ul>
            {% for reservation in customUser.carreservation_set.all %}
            <li> 
                <ul>
                    <li>
                        Car name: {{reservation.car.name}}
                    </li>
                    <li>
                        Start Date: {{reservation.startDate}}
                    </li>
                    <li>
                        End Date: {{reservation.endDate}}
                    </li>
                </ul>
            </li>
            {% endfor %}
        </ul>
        <a href="{% url 'product:addFunds' %}">Add funds to profile</a>
        {% if perms.auth.Manager %}
        <a href="{% url 'product:addCarPage' %}">Add car to database</a>
        <a href = "{% url 'product:payEmployeePage' %}">Pay Employees</a>
        {% endif %}
        {% if perms.auth.Employee or perms.auth.Manager %}
        <a href="{% url 'product:service' %}">Look at service tickets</a>
        <a href = "{% url 'product:employeeHours' %}">Log Hours</a>
        {% endif %}
        <a href = "{% url 'product:logoutPage' %}">Logout here</a>
    </div>
</body>
</html>

danshadybusiness/product/templates/product/displayCar.html
<!DOCTYPE html>

<html>
    <head>
        <title>Add Funds</title>
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'product/style/addFundsStyle.css' %}">
        <link rel="stylesheet" href="{% static 'product/style/headerStyle.css' %}">
        <link rel="stylesheet" href="{% static 'product/style/footerStyle.css' %}">
        <link rel="stylesheet" href="{% static 'product/style/style.css' %}">
        <script src="header.js"></script>
    </head>
    <body>
        {% include 'product/header.html' %}
        {% block content %}
        <div class="page">
            <h1>
                {{car.name}}
            </h1>
            <h1>
                Your current funds: ${{customUser.balance}}
            </h1>
            <h1>
                Reservation price per day: ${{car.price}}
            </h1>
            <h1>
                Reservation total: ${{totalPrice}}
            </h1>
            <h1>
                Reservation total with insurance: ${{totalPrice | add:50}}
            </h1>
            <form action = "{% url 'product:reserveCar' car.id %}" method = "post">
                {% csrf_token %}
                <label for = "startDate">
                    Start Date:
                </label>
                <input type = "date" value = {{startDate}} name = "startDate" id = "startDate" readonly>
                <label for = "endDate">
                    End Date:
                </label>
                <input type = "date" value = {{endDate}} name = "endDate" id = "endDate" readonly>
                <button class="button" type = "submit">Reserve Car</button>
                <br>
                <label for = "insurance">
                    Insurance? Price will be 50 dollars extra in total.
                </label>
                <select name = "insurance" id = "insurance">
                    <option>No</option>
                    <option>Yes</option>
                    

                </select>
            </form>
        </div>

        <h1>
            {{error}}
        </h1>

        {% include 'product/footer.html' %}
        {% endblock %}

    </body>
</html>

danshadybusiness/product/templates/product/employeeHours.html
<!DOCTYPE html>
<html>
    <body>
        <div class="page">
            <h1>
                Input your hours here: ...
            </h1>
            <form action="{% url 'product:logHours' %}" method="post">
                {% csrf_token %}
                <div>
                    <label for="hours"><b>Enter Hours</b></label>
                    <input type="number" placeholder="Enter Hours" name="hours" required>
                    <button type="submit">Log Hours</button>
                </div>
            </form>
        </div>
    </body>
</html>

danshadybusiness/product/templates/product/header.html
<!DOCTYPE html>
    {% load static %}
    <div class="header">
        <img src="{% static 'product/images/companyLogo.png' %}" alt="Company Logo" class="logo">
        <div class="container">
            <div class="row">
                <div class="title">
                    <div class="col-xs-3"></div>
                    <h1 class="title col-xs-6 text-center">Dan's Getaway Car Shack</h1>      
                </div>
                <div class="logout-ctn">
                    <a id="logout" href = "{% url 'product:logoutPage' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <div class="control-bar-container" onload="mobileView()">
        <div class="control-bar mobile-view" id="links">
            <a class="col-xs-12 col-sm-2 text-center link" id="home" href="{% url 'product:index' %}">Home</a>
            <a class="col-xs-12 col-sm-2 text-center link" id="add-funds" href="{% url 'product:addFunds' %}">Add Funds</a>
            <a class="col-xs-12 col-sm-2 text-center link" id="inventory" href = "{% url 'product:inventory' %}">Inventory</a>
            <a class="col-xs-12 col-sm-2 text-center link" id="reservation" href="{% url 'product:reservation' %}">Reservations</a>
            <a class="col-xs-12 col-sm-2 text-center link" id="about-us" href="{% url 'product:aboutUs' %}">About Us</a>
            <a class="col-xs-12 col-sm-2 text-center link" id="account" href="{% url 'product:account' %}">Account</a>
        </div>
    </div>
</div>

danshadybusiness/product/templates/product/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Add Funds</title>
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'product/style/style.css' %}">
        <link rel="stylesheet" href="{% static 'product/style/headerStyle.css' %}">
        <link rel="stylesheet" href="{% static 'product/style/footerStyle.css' %}">
    </head>
    <body>
        {% include 'product/header.html' %}
        {% block content %}
        <div class="page">
            <div class="container">
                <div class="row">
                    {% if perms.auth.Manager %}
                        <p>Welcome {{customUser.user.username}}. Here is a dashboard to handle your cars, employees, and service calls.</p>
                        <div class="dashboard-ctn">
                            <div class="col-sm-2"></div>
                            <a class="col-xs-12 col-sm-4 col-md-2 dashboard-link text-center" id="addCar" href="{% url 'product:addCarPage' %}"><button class="dashboard-button button">Add Car</button></a>
                            <a class="col-xs-12 col-sm-4 col-md-2 dashboard-link text-center" href = "{% url 'product:payEmployeePage' %}"><button class="dashboard-button button">Pay Employees</button></a>
                            <a class="col-xs-12 col-sm-4 col-md-2 dashboard-link text-center" href = "{% url 'product:hirePage' %}"><button class="dashboard-button button">Hire Employee</button></a>
                            <a class="col-xs-12 col-sm-4 col-md-2 dashboard-link text-center" href = "{% url 'product:service' %}"><button class="dashboard-button button">Service Tickets</button></a>
                            <div class="col-sm-2"></div>
                        </div>
                    {% elif perms.auth.Employee %}
                        <p>Welcome {{customUser.user.username}}. Here is a dashboard to log your hours and answer service calls.</p>
                        <div class="dashboard-ctn">
                            <div class="col-sm-3"></div>
                            <a class="col-xs-12 col-sm-3 dashboard-link text-center" id="addCar" href="{% url 'product:employeeHours' %}"><button class="dashboard-button button">Log Your Hours</button></a>
                            <a class="col-xs-12 col-sm-3 dashboard-link text-center" href = "{% url 'product:service' %}"><button class="dashboard-button button">Service Tickets</button></a>
                            <div class="col-sm-3"></div>
                        </div>
                    {% else %}
                        <p>Welcome {{customUser.user.username}}. Get your rental to make your quick getaway! Make sure to purchase the insurance... Wouldn't want you to break down... heh heh...</p>
                    {% endif %}
                </div>
            </div>
            {% include 'product/footer.html' %}
            {% endblock %}
        </div>
    </body>
</html>

danshadybusiness/product/templates/product/login.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'product/style/loginStyle.css' %}">
    <link rel="stylesheet" href="{% static 'product/style/footerStyle.css' %}">
    <title>Login</title>

</head>
<body>
    <div class="header" style="background-color:#1b263b;">
        <img src="{% static 'product/images/companyLogo.png' %}" alt="Company Logo" class="logo" style="max-width: 100px; max-height: 60px; ">
        <div class="container">
            <div class="row">
                <div class="title">
                    <div class="col-xs-3"></div>
                    <h1 class="title col-xs-6 text-center" style="color:white; text-shadow: 1px 1px 3px black;margin-top:-20px;">Dan's Getaway Car Shack</h1>
                    <div class="col-xs-3"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs">
            <div class = "container-fluid" id="formDiv">
                <form action="{% url 'product:loginTest' %}" method="post">
                {% csrf_token %}
                    <div>
                        <label for="username"><b>Username</b></label>
                        <input type="text" placeholder="Enter Username" name="username" required>
                        <label for="password"><b>Password</b></label>
                        <input type="password" placeholder="Enter Password" name="password" required>
                        <button type="submit">Login</button>
                        <a href="{% url 'product:signup' %}">Not a user?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% block content %}
{% include 'product/footer.html' %}
{% endblock %}
</body>

</html>

danshadybusiness/product/templates/product/reportHours.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Request Payment</title>
     {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'product/style/headerStyle.css' %}">
    <link rel="stylesheet" href="{% static 'product/style/footerStyle.css' %}">
    <link rel="stylesheet" href="{% static 'product/style/reportHoursStyle.css' %}">
</head>
<body>
 {% block content %}
 {% include 'product/header.html' %}


    <div id="reportContainer">

        <form action="{% url 'product:logHours' %}" method="post">
            {% csrf_token %}
            <div class="r">
        <label for="hours">Enter Hours worked</label>
            </div>
            <div class="r">
            <input type="number" name="hours" id="hours">
            </div>
            <div>
        <label for="certify"> I hereby certify the hours I have submitted are accurate</label>
            </div>
            <div>
            <input type="checkbox" id="certify" name="certify" required="required">
            </div>
            <button type="submit">Submit Hours for Manager Approval</button>
        </form>

    </div>
 {% include 'product/footer.html' %}
        {% endblock %}
</body>
</html>